apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-operator-focus-chart.fullname" . }}-repo-envvar
  labels:
  {{- include "finops-operator-focus-chart.labels" . | nindent 4 }}
data:
  REGISTRY: {{ .Values.env.REGISTRY | quote }}
