apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "finops-operator-focus-chart.fullname" . }}-manager
  labels:
  {{- include "finops-operator-focus-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - finops.krateo.io
  resources:
  - databaseconfigs
  verbs:
  - create
  - get
  - update
- apiGroups:
  - finops.krateo.io
  resources:
  - exporterscraperconfigs
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - finops.krateo.io
  resources:
  - focusconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - finops.krateo.io
  resources:
  - focusconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - finops.krateo.io
  resources:
  - focusconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - finops.krateo.io
  resources:
  - scraperconfigs
  verbs:
  - list
  - watch
