apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finops-operator-focus-chart.serviceAccountName" . }}
  labels:
  {{- include "finops-operator-focus-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}