apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finops-operator-focus-chart.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-focus
    app.kubernetes.io/part-of: operator-focus
  {{- include "finops-operator-focus-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}